name: CMake build

on:
  - push
  - pull_request

env:
  BUILD_TYPE: Release
  BUILD_GENERATOR: Ninja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install gperf
        run: |
          sudo apt-get update
          sudo apt-get install gperf

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G ${{env.BUILD_GENERATOR}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}